server:
  ip: 124.70.149.170
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rsa?serverTimezone=UTC
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

rsa:
  publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgfUoHdmvK5kb2DWbq67aEAFozH5PnKjFzDKIlSOudcBXgTC8ZqLEiqPBlAMu/UVocDcMW2pAONFgmGpDyW1slJgAj1HwI61opgdavgrNgLCp9fudRZagqA0lfguu/LzKmaz8JkPyxzEtNkp/Idic4pL9Z1rAa5JBkXCjQn0f4AeXbs2ssEQTJ1IH4lcSPuJkFuMCdii98aBLgormh1DZyzuW6SmmA6D4NzkufBms0iyquPxaWiMqzBrXXTzMVLzCm/szZbpp8JBmQQfP5es3dzts+CkfaslRrGbIbIJwYsNFl2VzbLyBdXQvWiRn+62PJZxZpkUDVP68YsBac0kmPQIDAQAB
  private: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCB9Sgd2a8rmRvYNZurrtoQAWjMfk+cqMXMMoiVI651wFeBMLxmosSKo8GUAy79RWhwNwxbakA40WCYakPJbWyUmACPUfAjrWimB1q+Cs2AsKn1+51FlqCoDSV+C678vMqZrPwmQ/LHMS02Sn8h2Jzikv1nWsBrkkGRcKNCfR/gB5duzaywRBMnUgfiVxI+4mQW4wJ2KL3xoEuCiuaHUNnLO5bpKaYDoPg3OS58GazSLKq4/FpaIyrMGtddPMxUvMKb+zNlumnwkGZBB8/l6zd3O2z4KR9qyVGsZshsgnBiw0WXZXNsvIF1dC9aJGf7rY8lnFmmRQNU/rxiwFpzSSY9AgMBAAECggEAMXWKFQI55o/Yxwpv+oELQLgomFsiFW8uCC7bSFdSGEJhiytvKGieAF2eWKR1h7KYssxgiZIAax9Uce1PayOYBV1sKR94Ezv17eoyoM0ftPCHXrSqAEf5ULvgHv53VHzNZnstY6rMhP60REtJ4ym7W4expVomjUoWZjHGEJHqRapSbrI5lEnnKh1UhJ8yOhwFZ9DxEEraV57IBAuSh6nNOD6MlzbVRjBNljiZU9/1G4vytdQtVJRrbzWggTa9UYbFkdTJpe+EgAqDcFv31OQi3KIyUHGHkzm0Er10mRXfZijb3p+5kMuP4GPdUUeWdCl1wsG/MO4OJHem4dn304zHQQKBgQDJwkj7qRbERIJPvo+CfsC3mRP2dFReYtXcIulmevPt25LeObfk5J9gV7trxcV2d5PE5iyGPADUg7O8f3VMxltZFSyVLsuE9ogMgmF38JfaBI8FJ0IUXsMBD+CnjthglDh3Yb1DZ8JopDNoz6QfM95Q1qY9KzpSMskMgMCto9JpWQKBgQCk5UU84KGk0H7lQo2qN75TN+3e0CyS7v4BEfVkA/F4kgjyRIraymqNpRaX6EJs4V7s02CjmmkywNkTxpH/cMdclocQZv81nR07hOQhOQvucnpUNKCXl4RsXDc6G/s5FmgiUQuE0E/f/1cXkoSjjmUIxSobttNw6vjUTc0T57NjhQKBgD1t7C7Dkuz7Nvn0uVkwIplEAHH/hVifmyHFd27+bJq1SghjZnxIp8X7sFLmCnNBgTpoIpJUXqRV3Tm9TQetNU7wRXy+nLTFIzM711Vfaby1up4FD/eHyrPeE7awpWzydCbVGX0WcHjP1d9JqVzevAe88yyYps80K0alRQUZZg0xAoGAKMU3VVIFJYcXmP/XnxqhSFovykOWgc3tp74U+mGvNqyE4cHowygBKHyFFZIrulgO7GdnIYxwLkhYY/dY6dusr0vYoUmWGF98dtbowP4l4RMVA/TvMAwaheBXF1sLxpWvsaxwOKp41V2A3ycu/HGcsYpuWuPda7HtTDDgX+eOBzECgYEAt5OA7rzwAJSnT/SsssNIa7pzXEpXA1qNc8+iPSd3shprofBUofqxmebdo9Fnzg60HYqKWu73Dk2cV2lfYJGNixyLXLV4iblTYJXwpeTP/Ive+eaQuWRdrASJco7dBX5QBokirfOTHNQARJDDhn7MIp1RG7BWQB/Uy9pGQ3LaZpU=